Switch to integer division for Py3.4 compatibility
This seems to be an issue with the switch to integer division, which in my current version is line 852 of sphtfunc.py. 
```
In [14]: import healpy as hp

In [15]: import numpy as np

In [16]: ell = np.arange(2,100)

In [17]: ee = 1/ell**2

In [18]: bb = 0.1/ell**2

In [19]: tt = ee*0

In [20]: te = ee*0

In [21]: m = hp.synfast((tt,te,ee,bb),nside, new=False, verbose=False)

In [22]: m = hp.synfast((tt,ee,bb,te),nside, new=True, verbose=False)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-22-821942e48991> in <module>()
----> 1 m = hp.synfast((tt,ee,bb,te),nside, new=True, verbose=False)

/home/dwatts/anaconda3/lib/python3.4/site-packages/healpy/sphtfunc.py in synfast(cls, nside, lmax, mmax, alm, pol, pixwin, fwhm, sigma, new, verbose)
    419     if lmax is None or lmax < 0:
    420         lmax = min(cls_lmax, 3 * nside - 1)
--> 421     alms = synalm(cls, lmax = lmax, mmax = mmax, new = new, verbose=verbose)
    422     maps = alm2map(alms, nside, lmax = lmax, mmax = mmax, pixwin = pixwin,
    423                    pol = pol, fwhm = fwhm, sigma = sigma, inplace = True, verbose=verbose)

/home/dwatts/anaconda3/lib/python3.4/site-packages/healpy/sphtfunc.py in synalm(cls, lmax, mmax, new, verbose)
    356         alms_list.append(alm)
    357     if new: # new input order: input given by diagonal, should be given by row
--> 358         cls_list = new_to_old_spectra_order(cls_list)
    359     # ensure cls are float64
    360     cls_list = [(np.asarray(cl, dtype = np.float64) if cl is not None else None)

/home/dwatts/anaconda3/lib/python3.4/site-packages/healpy/sphtfunc.py in new_to_old_spectra_order(cls_new_order)
    851             q = i
    852             idx_new = p * (2 * Nspec + 1 - p) / 2 + q
--> 853             cls_old_order.append(cls_new_order[idx_new])
    854     return cls_old_order
    855 

TypeError: list indices must be integers, not float
```